### ISSUE TITLE
Add Settings, Reset Etc

### ISSUE THREAD

**Issue by tracerrx** [dbjohnson/starlink-monitor#13]
Now that starlink is no longer deploying their javascript based web app with their routers ([now only accessible via mobile app)](https://www.reddit.com/r/Starlink/comments/1cautmg/starlink_web_app_not_available_what_do_i_do_now/) are there any plans to add changing Settings or Restarting dishy?

**Comment by dbjohnson** [comment]
No, there are no plans to add those features here.  It's just a simple monitor.
