### ISSUE TITLE
Obstruction Data inverted?

### ISSUE THREAD

**Issue by 0ff** [dbjohnson/starlink-monitor#14]
Love the dashboard, thank you so much for building it!

I'm trying to get the dish to have an unobstructed view and I was using your dashboard to debug it, when I realised: Something fishy is going on with dishy.

This is the obstruction map I see in the iOS App (North as reference - do note that dishy is pointed to north as well):
<img width="542" alt="image" src="https://github.com/dbjohnson/starlink-monitor/assets/1755213/3e933003-8824-4328-8cbf-11b101d1fa6b">

And this is what your monitor shows to me:
<img width="483" alt="image" src="https://github.com/dbjohnson/starlink-monitor/assets/1755213/637ba4ac-5422-4894-8a6a-3321b6253e3e">

Using dishy as a reference in the app (rather than pointing it north) also shows a different image:
<img width="530" alt="image" src="https://github.com/dbjohnson/starlink-monitor/assets/1755213/ad976c5c-644f-440b-be2a-9a08912e05d5">

So cross-referencing with the real world (which, I guess, is fair to assume to be correct) tells me that the obstructions are, relative to where dishy is pointed, on the top and right side.

Rotating the map in monitor would look like this this:
<img width="518" alt="image" src="https://github.com/dbjohnson/starlink-monitor/assets/1755213/ac478c57-5aa1-4067-9d1a-79109d447c04">
(turns out css-transform on #obstructions might not be the final solution :D)

Which leads me to assume that, at least for my particular case, the map shown on the dashboard might need to be rotated by 180 degrees. Would you be able to confirm that suspicion?

**Comment by 0ff** [comment]
On the same note: I've moved dishy to a slightly better position and I get way less outages, but according to the monitor it should get more (compared to the previous screenshot):
<img width="488" alt="image" src="https://github.com/dbjohnson/starlink-monitor/assets/1755213/04fff76e-b921-49c4-abce-7960cb851ed3">

   4.2% -> 2.5s every 16minutes
   0.3% -> 2.2s every 9 minutes

Is that actually the correct prediction here? 
Real-world says: I did not experience any 2s+ outages since the move (~2h ago)

**Comment by dbjohnson** [comment]
Re: the obstruction map, I went back and forth on this and honestly couldn't figure out the right orientation with the obstruction data from my dishy (there's no documentation available that I could find).  If you'd like to try changing it to try and match what you see (and are handy with js), here are the [relevant lines](https://github.com/dbjohnson/starlink-monitor/blob/d118a9bc3c56bc0c3de72c9894d7733aae7083b6/app/static/index.js#L341-L342).  I think for 180, you'd reverse both the x and y indices. If you give that a go and find that it matches the app better, I'd be happy to merge in a PR!

As for the downtime predictions, that comes directly from the API ([link](https://github.com/dbjohnson/starlink-monitor/blob/d118a9bc3c56bc0c3de72c9894d7733aae7083b6/app/static/index.js#L379)).  I haven't found it to be terribly accurate, either.
