### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by MyGreenBodhi** [dbjohnson/starlink-monitor#3]
I get this running the command...

"Successfully built 0a6ed8745a60
Successfully tagged starlink-monitor_flask:latest
Starting starlink-monitor_flask_1 ... error

ERROR: for starlink-monitor_flask_1  Cannot start service flask: error while creating mount source path '/starlink-monitor': mkdir /starlink-monitor: read-only file system

ERROR: for flask  Cannot start service flask: error while creating mount source path '/starlink-monitor': mkdir /starlink-monitor: read-only file system
ERROR: Encountered errors while bringing up the project."

It looks like a permission issue...but i'm not sure where to look

**Comment by dbjohnson** [comment]
Please give the pre-built image a try:

```
docker run -d -p 3000:80 \
    -e STARLINK_URI=192.168.100.1:9200 \
    -e STARLINK_REFRESH_SECS=1 \
    -e STARLINK_HISTORY_REFRESH_SECS=30 \
    -e BROADCAST_RATE_SECS=3 \
    -e SPEEDTEST_REFRESH_MINS=30 \
    -e BUFFER_SIZE_HOURS=72 \
    dbryanjohnson/starlink-monitor:latest
```

**Comment by MyGreenBodhi** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  That works perfectly, thank you                                                                                                                                                                                                                                                                                                                         From: notifications@github.comSent: February 15, 2021 9:52 PMTo: starlink-monitor@noreply.github.comReply-to: reply@reply.github.comCc: rob.dotten@mygreenbodhi.com; author@noreply.github.comSubject: Re: [dbjohnson/starlink-monitor] Error:  (#3)  
Please give the pre-built image a try:
docker run -d -p 3000:80 \
    -e STARLINK_URI=192.168.100.1:9200 \
    -e STARLINK_REFRESH_SECS=1 \
    -e STARLINK_HISTORY_REFRESH_SECS=30 \
    -e BROADCAST_RATE_SECS=3 \
    -e SPEEDTEST_REFRESH_MINS=30 \
    -e BUFFER_SIZE_HOURS=72 \
    dbryanjohnson/starlink-monitor:latest


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
