### ISSUE TITLE
Issue when trying to run a speed test.

### ISSUE THREAD

**Issue by LOCOMODDING** [dbjohnson/starlink-monitor#4]
When trying to run a speed test, I received the following error. Overall, I like the app though! Thanks!

flask_1 | File "/usr/local/lib/python3.9/site-packages/speedtest.py", line 1491, in get_best_server
flask_1 | raise SpeedtestBestServerFailure('Unable to connect to servers to '
flask_1 | speedtest.SpeedtestBestServerFailure: Unable to connect to servers to test latency.

**Comment by dbjohnson** [comment]
Looks like your connection must have been down while running the speedtest, or your host system has a firewall or other network config preventing connection.  Can you run speedtest-cli on the host machine?  In the container?
