### ISSUE TITLE
Odd peak in throughput graph...

### ISSUE THREAD

**Issue by kolonuk** [dbjohnson/starlink-monitor#5]
Firstly, thanks for your hard work on this!

My issue is that I have an oddity on the throughput graph, where it looks like a peak is offset slightly from where it should be, and the falling line goes back on itself.

It does seem to be accurate enough, isn't urgent, can't see it causing any problems etc., just rather odd!

![image](https://user-images.githubusercontent.com/5969835/111601784-9d789100-87ca-11eb-8903-dcdc81e72187.png)

**Comment by dbjohnson** [comment]
Hm, that's interesting - was there by any chance a starlink reboot during that time period?  Have you observed it again?

If you do see it again, please capture the raw data at `/api/data` so we can dig a little deeper.

**Comment by kolonuk** [comment]
This was a couple of weeks ago, so I don't think there was a reboot...  And no, not seen again, but I'll keep an eye out and certainly post the API data.
