### ISSUE TITLE
New install on Raspberry Pi: Not displaying any graphs

### ISSUE THREAD

**Issue by daytonturner** [dbjohnson/starlink-monitor#8]
Hi there

May have missed a step someplace - not sure, I've just installed the armhf tag following the instructions from the README exactly

The container starts and runs, I can load the page, and where I would expect the graphs to be, I see just a single button that says "Run speedtest now"

In the bottom left, I'm seeing:

History: 
15 mins
Updated: 1:11:05 PM
Uptime: 70.3 hours
Firmware: 86bab8ba-c91b-48a2-a495-e9ef466bad1c.uterm.release

(This was taken at 1:11 PM) 

This tells me it is able to read data from the starlink router, but not sure why the graphs/etc are missing. 

The only other thing I notice in the chrome javascript console output:

Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at renderPing (index.js:128)
    at render (index.js:114)
    at f.<anonymous> (index.js:87)
    at f.r.emit (index.js:145)
    at f.value (socket.js:271)
    at f.value (socket.js:258)
    at f.value (socket.js:223)
    at v.r.emit (index.js:145)
    at value (manager.js:211)
    at n.r.emit (index.js:145)

And nothing stands out as obviously wrong when tailing docker logs.

Any advice?

**Comment by drnikcuk** [comment]
Same issue here on a new install, did you find a resolution ?

**Comment by daytonturner** [comment]
The only thing I've found after researching this, is that starlink themselves modified the firmware a few weeks back which changed some of the stats API output.

For other projects, so I'm presuming this one as well, people found their projects were crashing in similar ways, due to getting unexpected/missing data back from the router. 

I suspect this is the same problem here.

**Comment by dbjohnson** [comment]
Thanks all - @daytonturner is correct that recent firmware updates have changed the data Starlink returns via API.  Namely, the SNR data is no longer provided, and downtime data has been reformatted.  These changes are addressed in https://github.com/dbjohnson/starlink-monitor/pull/9
